// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAutoLoginVal: typeof import('./src/components/AppAutoLoginVal.vue')['default']
    AppEducation: typeof import('./src/components/AppEducation.vue')['default']
    AppNaiveList: typeof import('./src/components/AppNaiveList.vue')['default']
    AppPhotoCard: typeof import('./src/components/AppPhotoCard.vue')['default']
    AppRankList: typeof import('./src/components/AppRankList.vue')['default']
    AppWarpChar: typeof import('./src/components/AppWarpChar.vue')['default']
    BaseBreadcrumb: typeof import('./src/components/BaseBreadcrumb.vue')['default']
    BaseEmpty: typeof import('./src/components/BaseEmpty.vue')['default']
    BaseMultipleDatePanel: typeof import('./src/components/BaseMultipleDatePanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    PanelCard: typeof import('./src/components/PanelCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
